University Site/University Site/Controllers/tableAproveController.cs
using Microsoft.AspNet.Identity;
using project_8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace project_8.Controllers
{
    [Authorize(Roles = "Accountant")]
    public class tableAproveController : Controller
    {
        private project8Entities db = new project8Entities();

        // GET: tableAprove
        public ActionResult Index(string search)
        {
            if (search == null)
            {

                var data = db.class_Accepted.Where(m => m.Accepted_Acountant == false).ToList();
                ViewBag.data = data;
                return View();
            }
            else
            {

                var data = db.class_Accepted.Where(m => m.Accepted_Acountant == false).Where(m => m.User_name.Contains(search)).ToList();
                ViewBag.data = data;
                return View();
            }
        }

        public ActionResult Paid(string id, int payment, string userName)
        {
            var class2 = db.class_Accepted.SingleOrDefault(m => m.User_id == id);
            class2.Accepted_Acountant = true;
            db.SaveChanges();
            int pay = payment;
            var newOne = new student_payments { User_id = id, User_name = userName, payment = payment, description = "Courses registration fees" };

            db.student_payments.Add(newOne);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

University Site/University Site/Views/tableAprove/Index.cshtml
@model List<project_8.Models.class_Accepted>

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
    ViewBag.Title = "Index";
}

<h2>Semester Hours Fees</h2>
<div class="ser" style="width:100%;overflow:auto">
    @using (Html.BeginForm("Index", "tableAprove", FormMethod.Get))

    {
        @Html.TextBox("search")
        <input type="Submit" value="search" class="btn btn-light" />
    }
</div>
<table class="table">
    <tr>
        <th>
            <span>UserName</span>
        </th>
        <th>
            <span>Charge</span>
        </th>

        <th>
            <span>Action</span>
        </th>
    </tr>

    @foreach (var item in ViewBag.data)
    {

        <tr>
            <td>
                <span>@item.User_name</span>
                @*@Html.LabelFor(m=>m.User_name)*@
            </td>
            <td>
                <span>@item.charge</span>
                @*@Html.LabelFor(m => m.charge)*@
            </td>
            <td>
                @Html.ActionLink("Paid", "Paid", new { id = item.User_id, payment = item.charge, userName = item.User_name }, new { @class = "btn btn-success" })

            </td>
        </tr>
    }

</table>