University Site/University Site/Controllers/AllowStudentController.cs
using project_8.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net.Mail;
using System.Security.Permissions;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;

namespace project_8.Controllers
{
    public class StudientTest
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string ID_number { get; set; }

        public string img { get; set; }

        public string ID_img { get; set; }

        public string certificate_img { get; set; }

        public string AVG { get; set;}

        public string major { get; set; }
    }
    public class AllowStudentController : Controller
    {
        private project8Entities db = new project8Entities();
        // GET: AllowEnrollment
        public ActionResult Index(string search)
        {
            if (search == null)
            {
                var data = db.AspNetUsers.Where(m => m.Acceptance == false).Include(m => m.Major).ToList();
                var result2 = db.AspNetUsers
                  .Where(m => m.Acceptance == false) // <-- add where clause
                  .Select(ss => new StudientTest
                  {
                      Id = ss.Id,
                      UserName = ss.UserName,
                      PhoneNumber = ss.PhoneNumber,
                      ID_number = ss.ID_number.ToString(),
                      img = ss.img,
                      ID_img = ss.ID_img.ToString(),
                      certificate_img = ss.certificate_img,
                      AVG = ss.AVG.ToString(),
                      major = ss.Major.Name,
                  })
                  .ToList();
                var dataaa = result2;
                ViewBag.data = dataaa;
                return View();
            }
            else
            {
                var data = db.AspNetUsers.Where(m => m.Acceptance == false).Include(m => m.Major).ToList();
                var result2 = db.AspNetUsers
                  .Where(m => m.Acceptance == false)  // <-- add where clause
                  .Where(m => m.UserName.Contains(search))
                  .Select(ss => new StudientTest
                  {
                      Id = ss.Id,
                      UserName = ss.UserName,
                      PhoneNumber = ss.PhoneNumber,
                      ID_number = ss.ID_number.ToString(),
                      img = ss.img,
                      ID_img = ss.ID_img.ToString(),
                      certificate_img = ss.certificate_img,
                      AVG = ss.AVG.ToString(),
                      major = ss.Major.Name,
                  })
                  .ToList();
                var dataaa = result2;
                ViewBag.data = dataaa;
                return View();


            }

        }


        public ActionResult Paid(string id)
        {
            var class2 = db.AspNetUsers.SingleOrDefault(m => m.Id == id);
            class2.Acceptance = true;
            db.SaveChanges();

            MailMessage mail = new MailMessage();
            mail.To.Add(class2.Email);
            mail.From = new MailAddress("ayahizzatalzyout@gmail.com");
            mail.Subject = "Accept";

            mail.Body = "Wellcom";
            mail.IsBodyHtml = true;

            SmtpClient smtp = new SmtpClient();
            smtp.Port = 587;
            smtp.EnableSsl = true;
            smtp.UseDefaultCredentials = false;
            smtp.Host = "smtp.gmail.com";
            smtp.Credentials = new System.Net.NetworkCredential("ayahizzatalzyout", "bpvxecfcoyngwhas");
            smtp.Send(mail);


            //int pay = payment;
            //var newOne = new student_payments { User_id = id, User_name = userName, payment = 250, description = "Semester fees" };

            //db.student_payments.Add(newOne);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

University Site/University Site/Views/AllowStudent/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
    ViewBag.Title = "Index";
}
<style>
    /* Default image size /*/
    img {
        width: 100px;
        height: auto;
    }

        /*/ Zoomed image size */
        img.zoom {
            width: 400px;
            height: auto;
        }

    .thumbnail {
        top: -50px;
        left: -35px;
        display: block;
        z-index: 999;
        cursor: pointer;
        -webkit-transition-property: all;
        -webkit-transition-duration: 0.3s;
        -webkit-transition-timing-function: ease;
    }

    .zoom {
        transform: scale(1.5); /* increase the size of the image by 50% */
    }

    .thumbnail:hover {
        transform: scale(5);
    }
</style>

<h2>Enrollment Forms</h2>
<hr />

<div class="ser" style="width:100%;overflow:auto">
    @using (Html.BeginForm("Index", "AllowStudent", FormMethod.Get))

    {
        @Html.TextBox("search")
        <input type="Submit" value="search" class="btn btn-light" />
    }
</div>

<table class="table">
    <tr>
        <th>
            <span>UserName</span>
        </th>
        <th>
            <span>PhoneNumber</span>
        </th>

        <th>
            <span>National Number</span>
        </th>
        <th>
            <span>Image</span>
        </th>
        <th>
            <span>ID image</span>
        </th>
        <th>
            <span>Certificate image</span>
        </th>
        <th>
            <span>Tawjehi AVG</span>
        </th>
        <th>
            <span>Major</span>
        </th>
        <th>
            <span>Action</span>
        </th>
    </tr>

    @foreach (var item in ViewBag.data)
    {

        <tr>
            <td>
                <span>@item.UserName</span>
            </td>
            <td>
                <span>@item.PhoneNumber</span>
            </td>
            <td>
                <span>@item.ID_number</span>
            </td>
            <td>
                <img id="img" class="thumbnail" src="@item.img" />
            </td>
            <td>
                <img class="thumbnail" src="@item.ID_img" />
            </td>
            <td>
                <img class="thumbnail" src="@item.certificate_img" />
            </td>
            <td>
                <span>@item.AVG</span>
            </td>
            <td>
                <span>@item.major</span>
            </td>

            <td>
                @Html.ActionLink("Accept", "Paid", new { id = item.Id }, new { @class = "btn btn-success" })

            </td>
        </tr>
    }

</table>

<script>
    console.log("running");
    // Get the image element
    const image = document.getElementById("img");

    // Add a click event listener
    image.addEventListener("click", function () {
        // Toggle a "zoom" class on the image
        this.classList.toggle("zoom");
    });


</script>