University Site/University Site/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using project_8.Models;

namespace project_8.Controllers
{
    [Authorize(Roles = "Ameed_IT")]
    public class ClassesController : Controller
    {
        private project8Entities db = new project8Entities();

        // GET: Classes
        public ActionResult Index()
        {
            var classes = db.Classes.Include(c => c.Cours);
            return View(classes.ToList());
        }

        // GET: Classes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.Classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }
            return View(@class);
        }

        // GET: Classes/Create
        public ActionResult Create(string search)
        {
            ViewBag.Courses_id = new SelectList(db.Courses, "Id", "Name");

            if (search == null)
            {
                var data = db.Classes.ToList();
                ViewBag.classe = data;

            }
            else
            {
                var data = db.Classes.Where(x => x.Cours.Name.Contains(search)).ToList();
                ViewBag.classe = data;
            }

          
            return View();
        }

        // POST: Classes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Courses_id,Time")] Class @class)
        {
            if (ModelState.IsValid)
            {
                db.Classes.Add(@class);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            ViewBag.Courses_id = new SelectList(db.Courses, "Id", "Name", @class.Courses_id);
            return View(@class);
        }

        // GET: Classes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.Classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }
            ViewBag.Courses_id = new SelectList(db.Courses, "Id", "Name", @class.Courses_id);
            return View(@class);
        }

        // POST: Classes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Courses_id,Time")] Class @class)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@class).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create");
            }
            ViewBag.Courses_id = new SelectList(db.Courses, "Id", "Name", @class.Courses_id);
            return View(@class);
        }

        // GET: Classes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.Classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }
            return View(@class);
        }

        // POST: Classes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Class @class = db.Classes.Find(id);
            db.Classes.Remove(@class);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

University Site/University Site/Views/Classes/Create.cshtml
@model project_8.Models.Class

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Classes</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2" style="text-align:left;width:150px;" for="Courses_id">Courses Name</label>

                <div class="col-md-10">
                    @Html.DropDownList("Courses_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Courses_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2", style = "text-align: left;width: 150px;" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.DropDownListFor(m => m.Time, new List<SelectListItem>
               {
                   new SelectListItem{Text = "08:00", Value="08:00:00"},
                   new SelectListItem{Text = "09:30", Value="09:30:00"},
                   new SelectListItem{Text = "11:00", Value="11:00:00"},
                   new SelectListItem{Text = "12:30", Value="12:30:00"},
                   new SelectListItem{Text = "02:00", Value="02:00:00"}
               }, "Select Time", new { @class = "form-control" })

                    @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <hr />

    <div class="ser" style="width:100%;overflow:auto">
        @using (Html.BeginForm("Create", "Classes", FormMethod.Get))

        {
            @Html.TextBox("search")
            <input type="Submit" value="search" class="btn btn-light" />
        }
    </div><br />



    <table class="table">
        <tr>
            <th>
                <span>Time</span>
            </th>
            <th>
                <span>Course Name</span>
            </th>
            <th></th>
        </tr>

        @foreach (var item in ViewBag.classe)
        {
            <tr>
                <td>
                    <span>@item.Time</span>

                </td>
                <td>
                    <span>@item.Cours.Name</span>
                </td>
                <td>

                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-success" }) |
                    @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

    </table>
</body>
</html>

University Site/University Site/Views/Classes/Delete.cshtml
@model project_8.Models.Class

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Class</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Time)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Time)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Cours.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Cours.Name)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Create")
            </div>
        }
    </div>
</body>
</html>

University Site/University Site/Views/Classes/Details.cshtml
@model project_8.Models.Class

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Class</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Time)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Time)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Cours.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Cours.Name)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

University Site/University Site/Views/Classes/Edit.cshtml
@model project_8.Models.Class

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}   


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Class</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Courses_id, "Courses_id", htmlAttributes: new { @class = "control-label col-md-2" , style = "text-align: left;width: 110px;" })
                <div class="col-md-10">
                    @Html.DropDownList("Courses_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Courses_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" , style = "text-align: left;width: 110px;" })
                <div class="col-md-10">
                   @* @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })*@

                    @Html.DropDownListFor(model => model.Time, new List<SelectListItem>
             {
                 new SelectListItem{Text = "08:00", Value="08:00:00"},
                 new SelectListItem{Text = "09:30", Value="09:30:00"},
                 new SelectListItem{Text = "11:00", Value="11:00:00"},
                 new SelectListItem{Text = "12:30", Value="12:30:00"},
                 new SelectListItem{Text = "02:00", Value="02:00:00"}
             }, "Select Time", new { @class = "form-control" })

                    @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Create")
    </div>
</body>
</html>

University Site/University Site/Views/Classes/Index.cshtml
@model IEnumerable<project_8.Models.Class>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cours.Name)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cours.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>