University Site/University Site/Models/Faculity.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculity()
        {
            this.Majors = new HashSet<Major>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string description { get; set; }
        public string img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Major> Majors { get; set; }
    }
}

University Site/University Site/Controllers/FaculitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using project_8.Models;


namespace project_8.Controllers
{
    [Authorize(Roles = "Admin")] 
    public class FaculitiesController : Controller
    {
        private project8Entities db = new project8Entities();

        // GET: Faculities
        public ActionResult Index()
        {
          return View(db.Faculities.ToList());
        }

        // GET: Faculities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculity faculity = db.Faculities.Find(id);
            if (faculity == null)
            {
                return HttpNotFound();
            }
            return View(faculity);
        }

        // GET: Faculities/Create
        public ActionResult Create(string search)
        {
            
            if (search == null)
            {
                var data = db.Faculities.ToList();
                ViewBag.Faculity = data;
                return View();

            }
            else
            {
                var data = db.Faculities.Where(x => x.Name.Contains(search)).ToList();
                ViewBag.Faculity = data;
                return View();


              
            }
            //return View();

        }

        // POST: Faculities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,description,img")] Faculity faculity, HttpPostedFileBase img)
        {
            if (ModelState.IsValid)
            {
                if (img != null)
                {
                    if (!img.ContentType.ToLower().StartsWith("image/"))
                    {
                        ModelState.AddModelError("", "file uploaded is not an image");
                        return View();
                    }
                    string folderPath = Server.MapPath("~/Content/Images");
                    if (!Directory.Exists(folderPath))
                    {
                        Directory.CreateDirectory(folderPath);
                    }
                    string fileName = Path.GetFileName(img.FileName);
                    string path = Path.Combine(folderPath, fileName);
                    img.SaveAs(path);
                    faculity.img = "../Content/Images/" + fileName;
                }
                else
                {
                    ModelState.AddModelError("", "Please upload an image.");
                    return View();
                }
                db.Faculities.Add(faculity);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(faculity);
        }

        // GET: Faculities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculity faculity = db.Faculities.Find(id);
            if (faculity == null)
            {
                return HttpNotFound();
            }
            return View(faculity);
        }

        // POST: Faculities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,description,img")] Faculity faculity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(faculity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create");
            }
            return View(faculity);
        }

        // GET: Faculities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculity faculity = db.Faculities.Find(id);
            if (faculity == null)
            {
                return HttpNotFound();
            }
            return View(faculity);
        }

        // POST: Faculities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Faculity faculity = db.Faculities.Find(id);
                db.Faculities.Remove(faculity);
                db.SaveChanges();
                
            } 
            catch (SqlException ex)
            {
                if (ex.Number == 547)
                {
                    
                    return RedirectToAction("Error");
                }
               
            }
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

University Site/University Site/Views/Faculities/Create.cshtml
@model project_8.Models.Faculity

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
    @*<a href="~/Views/Shared/_Layout1.cshtml">~/Views/Shared/_Layout1.cshtml</a>*@
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm("Create", "Faculities", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Faculity</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2", style = "text-align: left;width: 110px;" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2", style = "text-align: left;width: 110px;" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2 "  style="text-align: left;width: 110px;" for="img">img</label>
                <div class="col-md-10">
                    <input class=" text-box single-line" id="img" name="img" type="file" value="">
                    <span class="field-validation-valid text-danger" data-valmsg-for="img" data-valmsg-replace="true"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <br />
    <br />

    <div class="ser" style="width:100%;overflow:auto">
        @using (Html.BeginForm("Create", "Faculities", FormMethod.Get))

        { 
            @Html.TextBox("search")
            <input type="Submit" value="search" class="btn btn-light" />
        }
    </div><br />


    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.img)
            </th>
            <th></th>
        </tr>

        @foreach (var item in ViewBag.Faculity)
        {
            <tr>
                <td>
                    <span>@item.Name</span>
                </td>
                <td>
                    <span>@item.description</span>
                </td>
                <td>
                    <img src="../images/@item.img" alt="" style="width:100px;height:100px" class="thumbnail" />
                    @*<span>@item.img</span>*@
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-success" }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </table>




    @*<div>
            @Html.ActionLink("Back to List", "Index")
        </div>*@
</body>
</html>

University Site/University Site/Views/Faculities/Delete.cshtml
@model project_8.Models.Faculity

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
    @*<a href="~/Views/Shared/_Layout1.cshtml">~/Views/Shared/_Layout1.cshtml</a>*@
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Faculity</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.img)
            </dt>

            <dd>
                <img src="../@Model.img" alt="" style="width:100px;height:100px" />

            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Create")
            </div>
        }
    </div>
</body>
</html>

University Site/University Site/Views/Faculities/Details.cshtml
@model project_8.Models.Faculity

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
    @*<a href="~/Views/Shared/_Layout1.cshtml">~/Views/Shared/_Layout1.cshtml</a>*@
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Faculity</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.img)
            </dt>

            <dd>
              
                <img src="../@Model.img" alt="" style="width:100px;height:100px" />

            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Create")
    </p>
</body>
</html>

University Site/University Site/Views/Faculities/Edit.cshtml
@model project_8.Models.Faculity

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
    @*<a href="~/Views/Shared/_Layout1.cshtml">~/Views/Shared/_Layout1.cshtml</a>*@
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Faculity</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.img, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Create")
    </div>
</body>
</html>

University Site/University Site/Views/Faculities/Index.cshtml
@model IEnumerable<project_8.Models.Faculity>

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
    @*<a href="~/Views/Shared/_Layout1.cshtml">~/Views/Shared/_Layout1.cshtml</a>*@
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.img)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.img)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</body>
</html>